// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Sheet1_item : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static Sheet1_item GetRootAsSheet1_item(ByteBuffer _bb) { return GetRootAsSheet1_item(_bb, new Sheet1_item()); }
  public static Sheet1_item GetRootAsSheet1_item(ByteBuffer _bb, Sheet1_item obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Sheet1_item __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public short Hp { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }
  public short Mana { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }

  public static Offset<Sheet1_item> CreateSheet1_item(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      short hp = 0,
      short mana = 0) {
    builder.StartTable(3);
    Sheet1_item.AddName(builder, nameOffset);
    Sheet1_item.AddMana(builder, mana);
    Sheet1_item.AddHp(builder, hp);
    return Sheet1_item.EndSheet1_item(builder);
  }

  public static void StartSheet1_item(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddHp(FlatBufferBuilder builder, short hp) { builder.AddShort(1, hp, 0); }
  public static void AddMana(FlatBufferBuilder builder, short mana) { builder.AddShort(2, mana, 0); }
  public static Offset<Sheet1_item> EndSheet1_item(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Sheet1_item>(o);
  }
}


static public class Sheet1_itemVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Name*/, false)
      && verifier.VerifyField(tablePos, 6 /*Hp*/, 2 /*short*/, 2, false)
      && verifier.VerifyField(tablePos, 8 /*Mana*/, 2 /*short*/, 2, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
